const materials = [
  {
    id: 1,
    name: "Bioplástico de Almidón de Maíz",
    creator: "Dr. María González",
    category: "Bioplásticos",
    image: "/corn-starch-bioplastic-material.jpg",
    tags: ["Biodegradable", "Flexible", "Transparente"],
  },
  {
    id: 2,
    name: "Cuero de Micelio",
    creator: "Prof. Carlos Ramírez",
    category: "Textiles",
    image: "/mycelium-leather-sustainable-material.jpg",
    tags: ["Vegano", "Resistente", "Texturizado"],
  },
  {
    id: 3,
    name: "Compuesto de Fibra de Bambú",
    creator: "Dra. Ana Torres",
    category: "Compuestos",
    image: "/bamboo-fiber-composite-material.jpg",
    tags: ["Ligero", "Resistente", "Sostenible"],
  },
  {
    id: 4,
    name: "Bioespuma de Algas",
    creator: "Dr. Luis Fernández",
    category: "Espumas",
    image: "/algae-biofoam-sustainable-material.jpg",
    tags: ["Aislante", "Biodegradable", "Marino"],
  },
  {
    id: 5,
    name: "Papel de Residuos Agrícolas",
    creator: "Prof. Isabel Morales",
    category: "Papeles",
    image: "/agricultural-waste-paper-material.jpg",
    tags: ["Reciclado", "Texturizado", "Natural"],
  },
  {
    id: 6,
    name: "Bioresina de Pino",
    creator: "Dr. Roberto Silva",
    category: "Resinas",
    image: "/pine-bioresin-natural-material.jpg",
    tags: ["Adhesivo", "Natural", "Aromático"],
  },
];
export default materials;
